# Generated by Django 2.2.6 on 2020-06-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
